In [38]:
import numpy as np
import matplotlib.pyplot as plt

a = np.array(([1,2,3],[4,5,6],[7,8,9]))

b=np.array([1,0,1])
c=b.reshape(-1,1)

print a
print b
print c
print (a,c)
def f(*args):
    A,B = args
    print A
    print B

f(*(a,c))
print a.shape
q,r = a.shape
print q
print r


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 0 1]
[[1]
 [0]
 [1]]
(array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[1],
       [0],
       [1]]))
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [0]
 [1]]
(3, 3)
3
3
